### PR TITLE
Updated CI workflow for Xcode 12.4

### PR DESCRIPTION
**Pull request by bdrelling**
**Description**
We cannot use Xcode 12.5 or macOS 11.x yet, so the updates here are just for Xcode 12.4. Also, tvOS never received a 14.4 apparently?

Also updated to point to `main` per IOS-3011 and bumped gems, since some changed literally since last commit.

### CODE REVIEW

**Comment by bdrelling** [comment]
Linting fails because no lintable files are found.

**Comment by khaptonstall** [comment]
tvOS had a 14.4: https://developer.apple.com/documentation/tvos-release-notes/tvos-14_4-release-notes

**Review by khaptonstall — APPROVED** [review]
Not too worried about the tvOS bump, but there was a tvOS 14.4 (see my comment)

**Comment by bdrelling** [comment]
Yeah, it's odd--it's specifically like tvOS 14.4 isn't on GitHub's version of Xcode 12.4? It's very strange.

I'm sure when we update to Catalina it'll be fine, but like you said, not a huge concern.

**Pull request merged**
